### ISSUE TITLE
Can not clone repo

### ISSUE THREAD

**Issue by Pfed-prog** [dappradar/tokens#29]
fedor@kraken MINGW64 ~/github/pfed-prog
$ git clone https://github.com/Pfed-prog/tokens
Cloning into 'tokens'...
remote: Enumerating objects: 281897, done.
remote: Counting objects: 100% (6946/6946), done.
remote: Compressing objects: 100% (2956/2956), done.
Receiving objects: 100% (281897/281897), 1.91 GiB | 10.72 MiB/s, done.ed 274951

Resolving deltas: 100% (115516/115516), done.
error: invalid path 'everscale/0:01c8c8c678456e3bfbda8c8f655276b39af278a6527f3c42d8d1076ee6a68f5c/logo.png'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

fedor@kraken MINGW64 ~/github/pfed-prog/tokens (main)
$ git restore --source=HEAD :/
error: invalid path 'everscale/0:01c8c8c678456e3bfbda8c8f655276b39af278a6527f3c42d8d1076ee6a68f5c/logo.png'
error: invalid path 'everscale/0:01c8c8c678456e3bfbda8c8f655276b39af278a6527f3c42d8d1076ee6a68f5c/logo.svg'
error: invalid path 'everscale/0:03a878cfcb5475bbdeed030f0f274e2281ab26258c156747703ce9a761bce969/logo.png'
error: invalid path 'everscale/0:03a878cfcb5475bbdeed030f0f274e2281ab26258c156747703ce9a761bce969/logo.svg'
error: invalid path 'everscale/0:0cfa60f9454b1b619938c4da6a138b1cc62da937b3f6c0506405daf2a88e0115/logo.png'
error: invalid path 'everscale/0:0cfa60f9454b1b619938c4da6a138b1cc62da937b3f6c0506405daf2a88e0115/logo.svg'
error: invalid path 'everscale/0:1d5dce78bf1f4fadd3d75b57e3a1437504111fb6003e81f2edc6827f80b65e5e/logo.png'
error: invalid path 'everscale/0:1d5dce78bf1f4fadd3d75b57e3a1437504111fb6003e81f2edc6827f80b65e5e/logo.svg'
error: invalid path 'everscale/0:2ba32b75870d572e255809b7b423f30f36dd5dea075bd5f026863fceb81f2bcf/logo.png'
error: invalid path 'everscale/0:2ba32b75870d572e255809b7b423f30f36dd5dea075bd5f026863fceb81f2bcf/logo.svg'
error: invalid path 'everscale/0:4d23272c277c46b9f5c2f8ef4d39660b311c1878e46e356a4ae8546cfa761037/logo.png'
error: invalid path 'everscale/0:4d23272c277c46b9f5c2f8ef4d39660b311c1878e46e356a4ae8546cfa761037/logo.svg'
error: invalid path 'everscale/0:59b6b64ac6798aacf385ae9910008a525a84fc6dcf9f942ae81f8e8485fe160d/logo.png'
error: invalid path 'everscale/0:59b6b64ac6798aacf385ae9910008a525a84fc6dcf9f942ae81f8e8485fe160d/logo.svg'

**Comment by NedyalkoYotov** [comment]
hello @Pfed-prog the problem is it seems you are using WIndows, which finds contracts containing `:` as not valid paths. Everscale contracts however contain this symbol. You can check and see how sparse checkout works as this will be solution for you: https://git-scm.com/docs/git-sparse-checkout

**Comment by Pfed-prog** [comment]
I do not think there is a solution to this problem on windows 
https://stackoverflow.com/questions/5991805/how-do-i-clone-files-with-colons-in-the-filename

Is it possible to oultline how to contribute to the repo on Windows?

**Comment by dariusdev** [comment]
You can contribute using github web ui.
